[package]
name = "autoeth"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = { version = "2.0", features = ["rustls"] }
tokio = { version = "1", features = ["full"] }
eyre = "0.6"
dotenv = "0.15"
